### ISSUE TITLE
Confusion on part 2

### ISSUE THREAD

**Issue by HarshvardhanPatel123** [HarshvardhanPatel123/Group-Coursework-3-R#1]
Forgive me for deviating you away from question 1, but I can't seem to continue until I get more clarification on this.

Note that this function is supposed to work on any similar file that the user receives so
all of the sorting and processing should be done by code and not you picking out
particular rows e.g. do not look through the raw data see that row say 30 has an error
and then in your code select row 30 specifically rather than detecting it through code.  
Nor should you assume that there will always be the same number of rows but you can
assume that the first three columns will not contain any errors.

Do you understand what this means? Reading the rest of Q2 may help.

**Comment by nathbuen** [comment]
I think this part is saying that when you write the code, it should automatically handle any file that's similar to the one you're working with. You shouldn't manually pick out errors or specific rows. Instead, your code should be smart enough to find and fix these issues by itself. Also, you don't need to worry about the first three columns of the data; they won't have errors. This way, your code can work on different files without needing to change it every time.
