### ISSUE TITLE
Simplification

### ISSUE THREAD

**Issue by HarshvardhanPatel123** [HarshvardhanPatel123/Group-Coursework-3-R#2]
Do you think I can simplify this?

n <- policyholder_file$n[row]
      x <- policyholder_file$x[row]
      i <- policyholder_file$i[row]
      p <- policyholder_file$p[row]
      # After making the row values in the CSV file temporary variables, we can apply the function to it
      current_result <- ann.loan(type, n, x, i, p) # This uses the function in part i to gain a result per row

**Comment by nathbuen** [comment]
Just do：
result <- ann.loan(type, policyholder_file$n[row],
policyholder_file$x[row], policyholder_file$i[row],
policyholder_file$p[row])
